name-template: 'BitButler v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

branches:
  - main
disable-autolabeler: true

exclude-labels:
  - 'maintenance'
  - 'chore'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor']
  patch:
    labels: ['patch']
  default: patch

categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '📈 Enhancements'
    labels: ['enhancement']
  - title: '🪲 Bug Fixes'
    labels: ['bug']
  - title: '📦 Other Changes'
    labels: []

change-template: '- [#$NUMBER](https://github.com/enisz/bitbutler/pull/$NUMBER): $TITLE'
no-changes-template: '- Maintenance and internal improvements - no user-facing changes.'

template: |
  ## What's Changed

  $CHANGES
