name: 🪲 Bug Report
description: Report a reproducible bug
title: '[BUG]: '
labels: ['bug']
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: How did you encounter the bug?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: BitButler Version
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true
