name: 🚀 Feature Request
description: Suggest an idea for BitButler
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What should this feature do?
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      placeholder: Why is this feature useful?
