name: 🧰 Maintenance
description: Refactors, cleanups, or technical debt.
labels: ['maintenance']
body:
  - type: textarea
    id: goal
    attributes:
      label: Technical Goal
      placeholder: What are you cleaning up or refactoring?
    validations:
      required: true
