name: 🤔 Something Else
description: Anything that doesn't belong to any of the above.
title: '[OTHER]: '
labels: ['chore']
body:
  - type: textarea
    id: details
    attributes:
      label: What's on your mind?
      placeholder: Provide as much context as possible.
    validations:
      required: true
